spring:
  application:
    name: AuthJwtTemplate
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ProductForThar1?serverTimezone=UTC
    username: root
    password: root123

logging:
  level:
    org.springframework.security: TRACE

#logging:
#  level:
#    org.springframework.security: DEBUG
#    org.springframework.security.web: DEBUG
#    org.springframework.security.config: DEBUG